import type { Metadata } from 'next'
import './globals.css'
import Nav from './components/Nav'
import Camp from './components/Camp'
import DubNav from './components/DubNav'
import HomePage from './components/HomePage'
import Address from './components/Address'
import BigBanner from './components/BigBanner'
import DemoBanner from './components/DemoBanner'
import ScrollBanner from './components/ScrollBanner'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <>
          <DubNav />
          <HomePage />
          <Address />
          <DemoBanner/>
        </>
      </body>
    </html>
  )
}
